### ISSUE TITLE
Magnification causes app to break

### ISSUE THREAD

**Issue by ay13** [luwen-huang/angular-gulp-webpack-starter#3]
If you uncomment the line in gulpfile.js with the uglify plugin the minified version will not run correctly. It wont switch states or load in the lazy loaded file.

**Comment by luwen-huang** [comment]
Fixed. It turns out you need to repeat the name of the file in the "require.ensure" block within each lazy-loaded state.

**Comment by ay13** [comment]
What about the module js file? does it need to be repeated as well?

**Comment by luwen-huang** [comment]
No, I don't think so. Just within the templateProvider. (I think....)

**Comment by ay13** [comment]
hmm.. i built a small example for learning purposes off of your examples and blog posts (thanks by the way, helped a ton). if you are able can you look at what i did and see if you can find the error?

https://github.com/ay13/webpack-angular-oclazyload

works great except when minified.
